spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5440/cricket_db}
    username: ${DATABASE_USERNAME:cricket_user}
    password: ${DATABASE_PASSWORD:cricket_pass}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate


app:
  ipl:
    data-path: ${IPL_DATA_PATH:C:/Users/deepa/Desktop/ipl_json}
    import-enabled: ${IPL_IMPORT_ENABLED:true}
