package com.example.RCB_FanPage.DTO;

import com.example.RCB_FanPage.Entities.TeamEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import lombok.*;

import java.time.LocalDate;

@Builder
@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
public class Match {


    private Long id;   // match id (from JSON) - NOT autogenerated


    private Integer seasonYear;


    private LocalDate matchDate;


    private TeamEntity team1;

    private TeamEntity team2;


    private String venue;


    private String city;


    private TeamEntity winner;

    private String resultType;

    private Integer resultMargin;


    private TeamEntity tossWinner;

    private String tossDecision;

}
